AddDebateAnonymousVoteErrorCode:
    type: enum
    config:
        name: AddDebateAnonymousVoteErrorCode
        description: 'Available errors for an `addDebateAnonymousVote` mutation.'
        values:
            UNKNOWN_DEBATE:
                value: '@=constant("Capco\\AppBundle\\GraphQL\\Mutation\\Debate\\AddDebateAnonymousVoteMutation::UNKNOWN_DEBATE")'
                description: 'No `Debate` match your `debateId`.'
            CLOSED_DEBATE:
                value: '@=constant("Capco\\AppBundle\\GraphQL\\Mutation\\Debate\\AddDebateAnonymousVoteMutation::CLOSED_DEBATE")'
                description: 'The debate is closed and be voted.'
            INVALID_CAPTCHA:
                value: '@=constant("Capco\\AppBundle\\GraphQL\\Mutation\\Debate\\AddDebateAnonymousVoteMutation::INVALID_CAPTCHA")'
                description: 'The given captcha is invalid.'
