ArgumentOrderField:
    type: enum
    config:
        description: 'Properties by which argument connections can be ordered'
        values:
            PUBLISHED_AT:
                value: !php/const Capco\AppBundle\Enum\ArgumentOrderField::PUBLISHED_AT
                description: 'Allows ordering a list of arguments by when they were published.'
            VOTES:
                value: !php/const Capco\AppBundle\Enum\ArgumentOrderField::VOTES
                description: 'Allows ordering a list of arguments by the number of votes it have.'
