ContributionType:
  type: enum
  config:
    description: 'Different contribution type'
    values:
      OPINION:
        value: 'OPINION'
      OPINIONVERSION:
        value: 'OPINIONVERSION'
      COMMENT:
        value: 'COMMENT'
      ARGUMENT:
        value: 'ARGUMENT'
      SOURCE:
        value: 'SOURCE'
      PROPOSAL:
        value: 'PROPOSAL'
      REPLY:
        value: 'REPLY'
