DistrictOrderField:
  type: enum
  config:
    description: 'Ordering options for districts returned from the connection.'
    values:
      ALPHABETICAL:
        value: '@=constant("Capco\\AppBundle\\Enum\\DistrictOrderField::ALPHABETICAL")'
        description: 'Allows ordering a list of districts in an alphabetical order.'
      CREATED_AT:
        value: '@=constant("Capco\\AppBundle\\Enum\\DistrictOrderField::CREATED_AT")'
        description: 'Allows ordering a list of districts by when they were created.'
