HomePageProjectsSectionConfigurationDisplayMode:
    type: enum
    config:
        name: HomePageProjectsSectionConfigurationDisplayMode
        description: ''
        values:
            MOST_RECENT:
                description: display the most recents projects in the projects section of the homepage
                value: '@=constant("Capco\\AppBundle\\Enum\\HomePageProjectsSectionConfigurationDisplayMode::MOST_RECENT")'
            CUSTOM:
                description: allow the admin to choose which projects to display in the projects section of the homepage
                value: '@=constant("Capco\\AppBundle\\Enum\\HomePageProjectsSectionConfigurationDisplayMode::CUSTOM")'
