PostOrderField:
    type: enum
    config:
        description: 'Properties by which posts can be ordered'
        values:
            UPDATED_AT:
                value: '@=constant("Capco\\AppBundle\\Enum\\PostOrderField::UPDATED_AT")'
                description: 'Allows ordering a list of posts by when they have been updated.'
