ProposalTrashedStatus:
  type: enum
  config:
    description: 'Possible trashed status for a `Proposal`.'
    values:
      TRASHED:
        value: '@=constant("Capco\\AppBundle\\Enum\\ProposalTrashedStatus::TRASHED")'
        description: '`TRASHED` status to include the trashed proposal.'
      NOT_TRASHED:
        value: '@=constant("Capco\\AppBundle\\Enum\\ProposalTrashedStatus::NOT_TRASHED")'
        description: '`NOT_TRASHED` status to inclide the non trashed proposal.'
