RemoveProposalsFromStepsErrorCode:
  type: enum
  config:
    name: RemoveProposalsFromStepsErrorCode
    description: 'Available errors on step assignment of proposals'
    values:
      NO_VALID_PROPOSAL:
        value: '@=constant("Capco\\AppBundle\\Enum\\ProposalStepErrorCode::NO_VALID_PROPOSAL")'
        description: 'No proposal match your id or it does not fit the selected status'
      NO_VALID_STEP:
        value: '@=constant("Capco\\AppBundle\\Enum\\ProposalStepErrorCode::NO_VALID_STEP")'
        description: 'No step match your id or it does not fit the selected proposals'
