UpdateHomePageProjectsSectionConfigurationErrorCode:
    type: enum
    config:
        name: UpdateHomePageProjectsSectionConfigurationErrorCode
        description: 'Available errors for an `updateHomePageProjectsSectionConfiguration` mutation.'
        values:
            TOO_MANY_PROJECTS:
                value: '@=constant("Capco\\AppBundle\\GraphQL\\Mutation\\UpdateHomePageProjectsSectionConfigurationMutation::TOO_MANY_PROJECTS")'
                description: 'Limit of projects that can be dispayed in the homepage'
