updateCASSSOConfiguratonErrorCode:
    type: enum
    config:
        name: updateCASSSOConfiguratonErrorCode
        description: 'Available errors for an `updateCASSSOConfiguraton` mutation.'
        values:
            CONFIGURATION_NOT_FOUND:
                value: '@=constant("Capco\\AppBundle\\GraphQL\\Mutation\\UpdateCASSSOConfigurationMutation::CONFIGURATION_NOT_FOUND")'
                description: 'No CAS configuration matching the id.'
