VerifySmsVotePhoneNumberErrorCode:
    type: enum
    config:
        name: VerifySmsVotePhoneNumberErrorCode
        description: 'Available errors for an `verifySmsVotePhoneNumber` mutation.'
        values:
            CODE_EXPIRED:
                value: '@=constant("Capco\\AppBundle\\Helper\\TwilioHelper::CODE_EXPIRED")'
                description: 'The given code is expired.'
            CODE_NOT_VALID:
                value: '@=constant("Capco\\AppBundle\\Helper\\TwilioHelper::CODE_NOT_VALID")'
                description: 'The given code is not valid.'
            TWILIO_API_ERROR:
                value: '@=constant("Capco\\AppBundle\\Helper\\TwilioHelper::TWILIO_API_ERROR")'
                description: 'An error occured while calling twilio api.'
