Argument:
    type: object
    config:
        description: "An argument"
        interfaces: [Contribution, TrashableContribution, ContributionWithAuthor, EditableContribution]
        fields:
            createdAt:
                type: "String!"
                description: "Identifies the date and time when the object was created."
                resolve: "@=resolver('proposition_createdAt', [value])"
            updatedAt:
                type: "String!"
                description: "Identifies the date and time when the object was last updated."
                resolve: "@=resolver('proposition_updatedAt', [value])"
            url:
                type: "String!"
                resolve: "@=resolver('argument_url', [value])"
            expired:
                type: "Boolean!"
            published:
                type: "Boolean!"
            trashed:
                type: "Boolean!"
            trashedAt:
                type: "String"
                description: "Date of trash."
                resolve: "@=resolver('proposition_trashedAt', [value])"
            trashedReason:
                type: "String"
                description: "Reason of trash."
            author:
                type: "User!"
                description: "The author of the argument."
            type:
                type: "ArgumentValue!"
                description: "The type."
            votesCount:
                type: "Int!"
            id:
                type: "ID!"
                description: "The content of the argument."
            body:
                type: "String!"
                description: "The content of the argument."
            related:
                type: "Contribution"
                description: "Return the related contribution if the contribution is related to another."
            kind:
                type: "String!"
                description: "The kind of contribution (argument)."
