ChangeProposalEvaluationInput:
  type: relay-mutation-input
  config:
    fields:
      proposalId:
        type: 'ID!'
        description: 'The proposal id'
      version:
        type: 'Int!'
        description: 'The revision number of the evaluation'
      responses:
        type: '[ResponseInput!]!'
