ChangeSelectionStatusInput:
  type: relay-mutation-input
  config:
    description: ''
    fields:
      stepId:
        type: 'ID!'
      proposalId:
        type: 'ID!'
      statusId:
        type: 'ID'
