EditableContribution:
  type: interface
  config:
    description: 'A contribution with an author'
    resolveType: "@=resolver('contribution_type', [value])"
    fields:
      updatedAt:
        type: 'DateTime'
        description: 'Identifies the date and time when the object was last updated.'
