FollowOpinionInput:
  type: relay-mutation-input
  config:
    fields:
      opinionId:
        type: 'ID!'
        description: 'The opinion id'
      notifiedOf:
        type: 'SubscriptionTypeValue!'
        description: 'The type of notification'
