FollowerOrder:
  type: input-object
  config:
    description: 'Ways in which follower connections can be ordered.'
    fields:
      field:
        type: 'FollowerOrderField!'
        description: 'The field in which to order nodes by.'
      direction:
        type: 'OrderDirection!'
        defaultValue: 'ASC'
        description: 'The direction in which to order nodes.'
