InternalUserConnection:
  type: relay-connection
  config:
    name: UserConnection
    nodeType: InternalUser!
    connectionFields:
      totalCount:
        type: Int!
        description: Identifies the total count of items in the connection.
      anonymousCount:
        type: Int!
        description:
          Identifies the total count of anonymous items in the connection. (Not fetched from connection)
