MediaResponse:
  type: object
  config:
    interfaces: [Response]
    description: 'A response'
    fields:
      question:
        type: 'Question!'
      medias:
        type: '[Media!]!'
        description: 'Medias'
