NotRegistered:
  type: object
  config:
    description: 'A user without account.'
    fields:
      email:
        type: 'String'
        description: 'Email of the user.'
      username:
        type: 'String'
        description: 'Username of the user.'
