Opinion:
    type: object
    config:
        description: "A contribution"
        interfaces: [Contribution, TrashableContribution, ContributionWithAuthor, EditableContribution]
        fields:
            createdAt:
                type: "String!"
                description: "Identifies the date and time when the object was created."
                resolve: "@=resolver('proposition_createdAt', [value])"
            updatedAt:
                type: "String!"
                description: "Identifies the date and time when the object was last updated."
                resolve: "@=resolver('proposition_updatedAt', [value])"
            url:
                type: "URI!"
                description: "The HTTP url for this contribution."
                resolve: "@=resolver('proposition_url', [value])"
            author:
                type: "User!"
                description: "The author of the contribution."
            type:
                type: "OpinionType!"
            pinned:
                type: "Boolean!"
                description: "true if the contribution is pinned."
            expired:
                type: "Boolean!"
                description: "true if the contribution is expired."
            published:
                type: "Boolean!"
            trashed:
                type: "Boolean!"
                description: "true if the contribution is trashed."
            trashedAt:
                type: "String"
                description: "The moment the moderator trashed the contribution."
                resolve: "@=resolver('proposition_trashedAt', [value])"
            trashedReason:
                type: "String"
                description: "The reason the moderator trashed the contribution."
            votesCount:
                type: "Int!"
                description: "Number of votes."
                resolve: "@=resolver('proposition_votesCount', [value])"
            votesCountOk:
                type: "Int!"
                description: "Number of ok votes."
            votesCountMitige:
                type: "Int!"
                description: "Number of mitige votes."
            votesCountNok:
                type: "Int!"
                description: "Number of negative votes."
            connectionsCount:
                type: "Int!"
            argumentsCount:
                type: "Int!"
                description: "Number of arguments."
            argumentsCountFor:
                type: "Int!"
                description: "Number of for arguments."
                resolve: "@=resolver('proposition_argumentsCountFor', [value])"
            argumentsCountAgainst:
                type: "Int!"
                description: "Number of against arguments."
                resolve: "@=resolver('proposition_argumentsCountAgainst', [value])"
            versionsCount:
                type: "Int!"
                description: "Number of versions."
            sourcesCount:
                type: "Int!"
                description: "Number of sources."
            votes:
                type: "[PropositionVote]"
                args:
                    first:
                        type: "Int"
                resolve: "@=resolver('proposition_votes', [value, args])"
            id:
                type: "ID!"
                description: "The content of the contribution."
            related:
                type: "Contribution"
                description: "Return the related contribution if the contribution is related to another."
            kind:
                type: "String!"
                description: "The kind of contribution."
            title:
                type: "String!"
                description: "Identifies the contribution title."
            body:
                type: "HTML!"
                description: "Identifies the body of the contribution."
            bodyText:
                type: "String!"
                description: "Identifies the body of the contribution rendered to text."
            arguments:
                type: "[Argument]"
                args:
                    type:
                        description: "If omitted, returns all arguments. If provided, returns the arguments of this particular type."
                        type: "ArgumentValue"
                description: "The arguments related to the contribution."
                resolve: "@=resolver('proposition_arguments', [value, args])"
            versions:
                type: "[Version]"
                description: "The versions related to the contribution."
            sources:
                type: "[Source]"
                description: "The sources related to the contribution."
            section:
                type: "Section!"
                description: "Where the proposition has been placed."
                resolve: "@=resolver('proposition_section', [value])"
            reportings:
                type: "[Reporting]"
                resolve: "@=resolver('proposition_reportings', [value])"
