ProgressStep:
  type: object
  config:
    description: 'A budget contribution'
    fields:
      id:
        type: 'ID!'
      title:
        type: 'String!'
      startAt:
        type: 'DateTime!'
      endAt:
        type: 'DateTime'
