PropositionVote:
    type: object
    config:
        interfaces: [YesNoPairedVote, Contribution, ContributionWithAuthor]
        fields:
            id:
              type: "ID!"
            related:
                type: "Contribution"
                description: "The related proposition."
                # resolve: "@=resolver('proposition_vote_proposition', [value])"
            author:
                type: "User!"
                description: "The author of the contribution."
                resolve: "@=resolver('proposition_vote_author', [value])"
            value:
                type: "YesNoPairedVoteValue!"
            expired:
                type: "Boolean!"
                description: "If vote is expired, it exists but doesn't count."
            createdAt:
                type: "String!"
                description: "Date of vote."
                resolve: "@=resolver('vote_createdAt', [value])"
            related:
                type: "Contribution"
                description: "Return the related contribution if the contribution is related to another."
            kind:
                type: "String!"
                description: "Returns 'vote'."
