ProposalVotesOrder:
  type: input-object
  config:
    description: 'Ways in which lists of votes can be ordered upon return.'
    fields:
      field:
        type: 'VoteOrderField!'
        defaultValue: 'PUBLISHED_AT'
      direction:
        type: 'OrderDirection!'
        defaultValue: 'DESC'
