QuestionnaireType:
  type: enum
  config:
    description: 'Available questionnaire types.'
    values:
      QUESTIONNAIRE:
        value: '@=constant("Capco\\AppBundle\\Enum\\QuestionnaireType::QUESTIONNAIRE")'
        description: 'Draft are allowed.'
      VOTING:
        value: '@=constant("Capco\\AppBundle\\Enum\\QuestionnaireType::VOTING")'
        description: 'Draft are not allowed.'
