Reply:
  type: object
  inherits: [Node, Publishable, Draftable, Contribution]
  config:
    description: 'A Reply'
    interfaces: [Node, Publishable, Draftable, Contribution]
    fields:
      private:
        type: 'Boolean!'
      publicationStatus:
        type: 'ReplyPublicationStatus!'
        description: 'The reply status.'
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Reply\\ReplyPublicationStatusResolver", [value])'
      createdAt:
        type: 'DateTime!'
      responses:
        type: '[Response]!'
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Reply\\ReplyResponsesResolver", [value])'
      author:
        type: 'InternalUser!'
        description: 'The author of the contribution.'
      updatedAt:
        type: 'DateTime'
        description: 'The updated date.'
      questionnaire:
        type: 'InternalQuestionnaire!'
        description: 'Identifies the form where the contribution was submitted.'
      viewerCanUpdate:
        type: 'Boolean!'
        access: "@=hasRole('ROLE_USER')"
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Reply\\ReplyViewerCanUpdateResolver", [value, getUser()])'
      viewerCanDelete:
        type: 'Boolean!'
        access: "@=hasRole('ROLE_USER')"
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Reply\\ReplyViewerCanDeleteResolver", [value, getUser()])'
      show_url:
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Reply\\ReplyUrlResolver", [value])'
      url:
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Reply\\ReplyUrlResolver", [value])'
