UpdateQuestionnaireParametersInput:
  type: relay-mutation-input
  config:
    description: ''
    fields:
      questionnaireId:
        type: 'ID!'
      acknowledgeReplies:
        type: 'Boolean'
      anonymousAllowed:
        type: 'Boolean'
      multipleRepliesAllowed:
        type: 'Boolean'
      phoneConfirmation:
        type: 'Boolean'
