VersionOrderField:
  type: enum
  config:
    description: 'Properties by which version connections can be ordered'
    values:
      PUBLISHED_AT:
        value: 'PUBLISHED_AT'
        description: 'Allows ordering a list of versions by when they were published.'
      VOTES:
        value: 'VOTES'
        description: 'Allows ordering a list of versions by the number of votes it have.'
      ARGUMENTS:
        value: 'ARGUMENTS'
        description: 'Allows ordering a list of versions by the number of arguments it have.'
      VOTES_OK:
        value: 'VOTES_OK'
        description: 'Allows ordering a list of versions by the number of votes ok it have.'
      RANDOM:
        value: 'RANDOM'
        description: 'Allows ordering a list of versions randomly.'
