Version:
    type: object
    config:
        description: "A version of contribution"
        interfaces: [Contribution, TrashableContribution, ContributionWithAuthor, EditableContribution]
        fields:
            createdAt:
                type: "String!"
                description: "Identifies the date and time when the object was created."
                resolve: "@=resolver('proposition_createdAt', [value])"
            updatedAt:
                type: "String!"
                description: "Identifies the date and time when the object was last updated."
                resolve: "@=resolver('proposition_updatedAt', [value])"
            url:
                type: "String!"
                description: "The url of version."
                resolve: "@=resolver('version_url', [value])"
            author:
                type: "User!"
                description: "The author of the contribution."
            expired:
                type: "Boolean!"
            published:
                type: "Boolean!"
            trashed:
                type: "Boolean!"
            trashedAt:
                type: "String"
                description: "Date of trash."
                resolve: "@=resolver('proposition_trashedAt', [value])"
            trashedReason:
                type: "String"
                description: "Reason of trash."
            comment:
                type: "String"
                description: "Explenation."
            votesCount:
                type: "Int!"
                description: "Number of votes."
                resolve: "@=resolver('proposition_votesCount', [value])"
            votesCountOk:
                type: "Int!"
                description: "Number of ok votes."
            votesCountMitige:
                type: "Int!"
                description: "Number of mitige votes."
            votesCountNok:
                type: "Int!"
                description: "Number of negative votes."
            argumentsCount:
                type: "Int!"
                description: "Number of arguments."
            argumentsCountFor:
                type: "Int!"
                description: "Number of for arguments."
                resolve: "@=resolver('proposition_argumentsCountFor', [value])"
            argumentsCountAgainst:
                type: "Int!"
                description: "Number of against arguments."
                resolve: "@=resolver('proposition_argumentsCountAgainst', [value])"
            sourcesCount:
                type: "Int!"
                description: "Number of sources."
            votes:
                type: "[VersionVote]"
                args:
                    first:
                        type: "Int"
                resolve: "@=resolver('version_votes', [value, args])"
            id:
                type: "ID!"
                description: "The content of the contribution."
            related:
                type: "Contribution"
                description: "Return the related contribution if the contribution is related to another."
            kind:
                type: "String!"
                description: "Returns 'version'."
            title:
                type: "String!"
                description: "The title of the contribution."
            body:
                type: "HTML!"
                description: "The content of the contribution."
            bodyText:
                type: "HTML!"
                description: "The content of the contribution."
            arguments:
                type: "[Argument]"
                args:
                    type:
                        description: "If omitted, returns all arguments. If provided, returns the arguments of this particular type."
                        type: "ArgumentValue"
                description: "The arguments related to the contribution."
                resolve: "@=resolver('proposition_arguments', [value, args])"
            sources:
                type: "[Source]"
                description: "The sources related to the contribution."
            reportings:
                type: "[Reporting]"
                resolve: "@=resolver('version_reportings', [value])"
