VersionOrder:
  type: input-object
  config:
    description: 'Ways in which version connections can be ordered.'
    fields:
      field:
        type: 'VersionOrderField!'
        description: 'The field in which to order nodes by.'
      direction:
        type: 'OrderDirection!'
        defaultValue: 'ASC'
        description: 'The ordering direction.'
