sonata_doctrine_orm_admin:
    templates:
        form: [CapcoAdminBundle:Form:form_admin_fields.html.twig]

sonata_intl:
    timezone:
        detectors:
            - Capco\AdminBundle\Timezone\GlobalConfigurationTimeZoneDetector
        locales:
            default: Europe/Paris
            fr-FR: Europe/Paris
            en-GB: Europe/London
            de-DE: Europe/Berlin
            nl-NL: Europe/Berlin
            sv-SE: Europe/Berlin
            eu-EU: Europe/Berlin
            oc-OC: Europe/Berlin
            ur-IN: Europe/Berlin

knp_doctrine_behaviors:
    translatable: true
    geocodable: false
    loggable: false
    sluggable: false
    soft_deletable: false
