services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  Capco\AppBundle\Synthesis\Extractor\:
    resource: '%kernel.root_dir%/../src/Capco/AppBundle/Synthesis/Extractor/*'

  Capco\AppBundle\Synthesis\:
    resource: '%kernel.root_dir%/../src/Capco/AppBundle/Synthesis/*'

  Capco\AppBundle\Synthesis\Handler\SynthesisHandler:
    autowire: true
    public: true

  Capco\AppBundle\Synthesis\Handler\SynthesisElementHandler:
    autowire: true
    public: true
