qandidate_toggle:
  persistence: redis
  context_factory: null
  redis_namespace: '%redis_prefix%feature_toggle' # default, only required when persistence = redis
  redis_client: snc_redis.default # only required when persistence = redis
