when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false
        excluded_ajax_paths: '^/((index|app(_[\w]+)?)\.php/)?_wdt'

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
