capco_locale:
    resource: '@CapcoAppBundle/Controller/Api/LocaleController.php'
    type: annotation
    prefix: /
    options: { i18n: false }

# BO
capco_admin:
    resource: '../../src/Capco/AdminBundle/Controller/'
    type: annotation
    prefix: /
    options: { i18n: false }

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    options: { i18n: false }

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    options: { i18n: false }

sonata_translation:
    resource: '@SonataTranslationBundle/Resources/config/routes.yaml'
    options: { i18n: false }

# GraphQL
capco_graphql:
    resource: '@CapcoAppBundle/Controller/Api/GraphQLController.php'
    type: annotation
    prefix: /
    options: { i18n: false }

capco_graphiql:
    resource: '@CapcoAppBundle/Controller/Api/GraphiQLController.php'
    type: annotation
    prefix: /
    options: { i18n: false }

# API

capco_api_medias:
    resource: '@CapcoAppBundle/Controller/Api/MediasController.php'
    type: annotation
    prefix: /api
    defaults:
        _format: json
    options: { i18n: false }

capco_api_fonts:
    resource: '@CapcoAppBundle/Controller/Api/FontsController.php'
    type: annotation
    prefix: /api
    defaults:
        _format: json
    options: { i18n: false }

capco_api_webcomponent:
    resource: '@CapcoAppBundle/Controller/Api/SiradelController.php'
    type: annotation
    prefix: /api
    defaults:
        _format: json
    options: { i18n: false }

capco_api_sendinblue:
    resource: '@CapcoAppBundle/Controller/Api/SendInBlueController.php'
    type: annotation
    prefix: /api
    defaults:
        _format: json
    options: { i18n: false }

capco_api_sso:
    resource: '@CapcoAppBundle/Controller/Api/SSOController.php'
    type: annotation
    prefix: /api
    defaults:
        _format: json
    options: { i18n: false }

# App
capco_app:
    resource: '@CapcoAppBundle/Controller/Site'
    type: annotation
    prefix: /

admin_capco_media_media_list:
    path: /admin/capco/media/media/list
    controller: Capco\AdminBundle\Controller\MediaAdminController::listAction
    defaults:
        _sonata_admin: sonata.media.admin.media
    options: { i18n: false }

# Dummy route for fos
fos_user_profile_show:
    path: /profile/redirect-fos-show
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: capco_user_profile_show
        permanent: true
    options: { i18n: false }

capco_profile_edit:
    path: /profile/edit-profile
    defaults: { _controller: CapcoUserBundle:Profile:editProfile }
    options: { i18n: false }

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
    options: { i18n: false }

#These routes must be translated for they render html
fos_user_resetting_request:
    path: /resetting/request
    defaults: { _controller: Capco\UserBundle\Controller\ResettingController::requestAction }

fos_user_resetting_reset:
    path: /resetting/reset/{token}
    defaults: { _controller: Capco\UserBundle\Controller\ResettingController::resetAction }

fos_user_resetting_send_email:
    path: /resetting/send-email
    defaults: { _controller: Capco\UserBundle\Controller\ResettingController::sendEmailAction }

fos_user_resetting_check_email:
    path: /resetting/check-email
    defaults: { _controller: Capco\UserBundle\Controller\ResettingController::checkEmailAction }
#end

capco_user:
    resource: '@CapcoUserBundle/Controller/'
    type: annotation
    prefix: /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery
    options: { i18n: false }

# sonata media
media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    options: { i18n: false }

# liip imagine
_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'
    options: { i18n: false }

#HWIOAuthBundle routes
hwi_oauth:
    resource: '@CapcoUserBundle/Resources/config/routing.xml'
    prefix: /login
    options: { i18n: false }

facebook_login:
    path: /login/check-facebook
    options: { i18n: false }

google_login:
    path: /login/check-google
    options: { i18n: false }

openid_login:
    path: /login/check-openid
    options: { i18n: false }

franceconnect_login:
    path: /login/check-franceconnect
    options: { i18n: false }

_translation_edit_in_place:
    resource: '@TranslationBundle/Resources/config/routing_edit_in_place.yaml'
    prefix: /admin
    options: { i18n: false }

capco_app_cms:
    path: /{url}
    defaults: {} # no default, only use for generation...
    options: { i18n: false }
    requirements:
        methods: GET
        url: '^.*$'
