InternalPrimaryKey:
  decorator: true
  config:
    fields:
      _id:
        type: 'ID'
        description: 'Expose Primary Key, do not use it, except for testing purpose.'
        resolve: '@=value.getId()'
