PreviewProjectOrder:
  type: input-object
  config:
    name: ProjectOrder
    description: 'Ways in which project can be ordered.'
    fields:
      direction:
        type: 'OrderDirection!'
        description: 'The direction in which to order nodes.'
      field:
        type: 'PreviewProjectOrderField!'
        description: 'The field in which to order nodes by.'
