PreviewResponseConnection:
  type: relay-connection
  config:
    name: ResponseConnection
    nodeType: PreviewResponse!
    connectionFields:
      totalCount:
        type: Int!
        description: Identifies the total count of items in the connection.
