PreviewProjectConnection:
  type: relay-connection
  config:
    name: ProjectConnection
    nodeType: PreviewProject!
    connectionFields:
      totalCount:
        type: Int!
        description: Identifies the total count of items in the connection.
