PreviewVoteConnection:
  type: relay-connection
  config:
    name: VoteConnection
    nodeType: PreviewVote
    connectionFields:
      totalCount:
        type: Int!
        description: Identifies the total count of items in the connection.
