imports:
    - { resource: config_dev.yml }

framework:
  test: ~
  profiler:
    collect: false
  translator:
    enabled: false

translation:
    symfony_profiler:
        enabled: false

qandidate_toggle:
    redis_namespace: feature_toggle_test

web_profiler:
  toolbar: false
  intercept_redirects: false

services:
    # We disable captcha validation
    capco.recaptcha.validator:
          class: Capco\AppBundle\Validator\Constraints\ReCaptchaValidator
          arguments: ["@request_stack", '%recaptcha_private_key%', '@capco.toggle.manager', false]
          tags:
              - { name: validator.constraint_validator, alias: recaptcha.validator }

monolog:
    handlers:
        main:
            type:   stream
            path:   php://stderr
            level:  warning
        file:
            type: stream
            path: "%kernel.logs_dir%/test.log"
            level: debug
