liip_imagine:
  resolvers:
    default:
      web_path: ~
  loaders:
    default:
      filesystem:
        data_root: '%kernel.root_dir%/../web/media'
  driver: imagick
  filter_sets:
    cache: ~
    admin:
      quality: 100
      filters:
        thumbnail: { size: [100, 100], mode: outbound }

    default_avatar:
      quality: 70
      filters:
        thumbnail: { size: [45, 45], mode: outbound }

    default_avatar_source:
      quality: 70
      filters:
        thumbnail: { size: [32, 32], mode: outbound }

    default_big:
      quality: 75
      filters:
        thumbnail: { size: [500, 70], mode: outbound }

    default_blockHeader:
      quality: 100
      filters:
        thumbnail: { size: [750, 500], mode: outbound }

    default_project:
      quality: 100
      filters:
        thumbnail: { size: [360, 240], mode: outbound }
        crop: { start: [0, 0], size: [360, 240] }

    default_post:
      quality: 80
      format: png
      filters:
        thumbnail: { size: [225, 150], mode: inbound }

    default_form:
      quality: 70
      filters:
        relative_resize: { heighten: 150 }

    default_idea:
      quality: 70
      filters:
        relative_resize: { heighten: 400 }

    default_proposal:
      quality: 70
      filters:
        relative_resize: { heighten: 400 }

    default_response:
      quality: 70
      filters:
        relative_resize: { heighten: 400 }

    default_logo:
      quality: 70
      filters:
        relative_resize: { heighten: 50 }

    default_profile:
      quality: 100
      filters:
        upscale: { min: [200, 200] }
        thumbnail: { size: [200, 200], mode: outbound }

    default_small:
      quality: 75
      filters:
        thumbnail: { size: [100, 70], mode: outbound }

    favicon_16:
      quality: 70
      filters:
        thumbnail: { size: [16, 16], mode: inbound }

    favicon_32:
      quality: 70
      filters:
        thumbnail: { size: [32, 32], mode: inbound }

    favicon_57:
      quality: 70
      filters:
        thumbnail: { size: [57, 57], mode: inbound }

    favicon_60:
      quality: 70
      filters:
        thumbnail: { size: [60, 60], mode: inbound }

    favicon_70:
      quality: 70
      filters:
        thumbnail: { size: [70, 70], mode: inbound }

    favicon_72:
      quality: 70
      filters:
        thumbnail: { size: [72, 72], mode: inbound }

    favicon_76:
      quality: 70
      filters:
        thumbnail: { size: [76, 76], mode: inbound }

    favicon_96:
      quality: 70
      filters:
        thumbnail: { size: [96, 96], mode: inbound }

    favicon_114:
      quality: 70
      filters:
        thumbnail: { size: [114, 114], mode: inbound }

    favicon_120:
      quality: 70
      filters:
        thumbnail: { size: [120, 120], mode: inbound }

    favicon_144:
      quality: 70
      filters:
        thumbnail: { size: [144, 144], mode: inbound }

    favicon_150:
      quality: 70
      filters:
        thumbnail: { size: [150, 150], mode: inbound }

    favicon_152:
      quality: 70
      filters:
        thumbnail: { size: [152, 152], mode: inbound }

    favicon_180:
      quality: 70
      filters:
        thumbnail: { size: [180, 180], mode: inbound }

    favicon_310:
      quality: 70
      filters:
        thumbnail: { size: [310, 310], mode: inbound }

    default_socialIcon:
      quality: 70
      filters:
        thumbnail: { size: [50, 50], mode: inbound }

    default_header:
      quality: 70
      filters:
        relative_resize: { widen: 1280 }

    default_header_xs:
      quality: 70
      filters:
        relative_resize: { widen: 640 }

    default_shield:
      quality: 70

    default_header_sm:
      quality: 70
      filters:
        relative_resize: { widen: 800 }

    default_header_md:
      quality: 70
      filters:
        relative_resize: { widen: 1024 }

    default_header_picto:
      quality: 70
      filters:
        relative_resize: { heighten: 100 }

    default_form_radio:
      quality: 70
      filters:
        thumbnail: { size: [847, 847], mode: outbound, allow_upscale: false }

    default_img_video:
      quality: 70
      filters:
        relative_resize: { widen: 320 }

    default_homepageVideo:
      quality: 100
      filters:
        thumbnail: { size: [360, 240], mode: outbound }
        crop: { start: [0, 0], size: [360, 240] }

    default_theme:
      quality: 100
      filters:
        thumbnail: { size: [360, 240], mode: outbound }
        crop: { start: [0, 0], size: [360, 240] }

    default_slider:
      quality: 70
      filters:
        upscale: { min: [800, 500] }
        thumbnail: { size: [800, 500], mode: outbound }
        crop: { start: [0, 0], size: [800, 500] }
