security:
  acl:
    connection: default

  encoders:
    Capco\UserBundle\Entity\User: bcrypt
    drupal:
      id: Capco\UserBundle\Security\DrupalEncoder

  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    SONATA:
      - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT # if you are using acl then this line must be commented

  providers:
    fos_userbundle:
      id: Capco\UserBundle\Security\Core\User\UserEmailProvider
    simple_preauth:
      id: Capco\UserBundle\Security\Core\User\SimplePreAuthenticatorUserProvider
    public_api_key_user_provider:
      id: Capco\AppBundle\PublicApi\PublicApiKeyUserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # This is our Public API authenticated with Personal Access Token
    graphql_public:
      pattern: ^/graphql$
      provider: public_api_key_user_provider
      stateless: true
      anonymous: true # Right now anonymous are allowed
      simple_preauth:
        authenticator: Capco\AppBundle\PublicApi\PublicApiKeyAuthenticator

    # The rest is authenticated with cookies
    main:
      pattern: ^/
      provider: fos_userbundle
      anonymous: true
      simple_preauth:
        authenticator: Capco\UserBundle\Authenticator\SimplePreAuthenticator
        provider: simple_preauth
      json_login:
        check_path: /login_check
        remember_me: true
      oauth:
        resource_owners:
          facebook: /login/check-facebook
          google: /login/check-google
          openid: /login/check-openid
        login_path: /
        oauth_user_provider:
          service: Capco\UserBundle\Security\Core\User\OauthUserProvider
      remember_me:
        always_remember_me: false
        secret: '%remember_secret%'
        lifetime: 31536000
        path: /
        domain: ~
      logout:
        path: /logout
        success_handler: Capco\UserBundle\Security\Http\Logout\LogoutSuccessHandler
        logout_on_user_change: true

  access_control:
    - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
