sonata_admin:
  title: Cap Collectif
  title_logo: favicon-64x64.png
  assets:
    remove_javascripts:
      - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
  options:
    pager_links: 5 # pager max links to display
  templates:
    layout: CapcoAdminBundle::standard_layout.html.twig
    list_block: CapcoAdminBundle:Block:block_admin_list.html.twig
    add_block: CapcoAdminBundle:Core:add_block.html.twig
  dashboard:
    blocks:
      - {
          position: left,
          type: sonata.admin.block.admin_list,
          settings: { groups: [admin.group.moderation] },
        }
      - {
          position: right,
          type: capco_admin.block.help,
          settings: { title: admin.label.help_block },
        }
      - {
          position: right,
          type: capco_admin.block.recent_contributions,
          settings: { number: 5, title: admin.label.recent_contributions },
        }
      - {
          position: left,
          type: capco_admin.blog.block.recent_posts,
          settings: { number: 7, title: admin.label.recent_posts, toggle: 'blog' },
        }
    groups:
      admin.group.moderation:
        items:
          - capco_admin.admin.reporting
          - capco_admin.admin.proposal
          - capco_admin.admin.opinion
          - capco_admin.admin.reply
          - capco_admin.admin.opinion_version
          - capco_admin.admin.argument
          - capco_admin.admin.source
          - capco_admin.admin.comment
      admin.group.content:
        items:
          - capco_admin.admin.highlighted
          - capco_admin.admin.theme
          - capco_admin.admin.post
          - capco_admin.admin.event
          - capco_admin.admin.video
          - capco_admin.admin.page
          - sonata.media.admin.media
      admin.group.project:
        items:
          - capco_admin.admin.project
          - capco_admin.admin.appendix_type
          - capco_admin.admin.category
          - capco_admin.admin.consultation_step_type
          - capco_admin.admin.proposal_form
          - capco_admin.admin.questionnaire
          - capco_admin.admin.project_type
      sonata.admin.group.user:
        items:
          - sonata.user.admin.user
          - capco_admin.admin.group
          - capco_admin.admin.user_type
          - capco_admin.admin.newsletter_subscription
      admin.group.parameters:
        items:
          - capco_admin.admin.menu_item
          - capco_admin.admin.social_network
          - capco_admin.admin.footer_social_network
          - capco_admin.admin.project_district
          - capco_admin.admin.map
          - capco_admin.admin.site_favicon
      admin.group.pages:
        items:
          - capco_admin.admin.section

sonata_doctrine_orm_admin:
  templates:
    form: [CapcoAdminBundle:Form:form_admin_fields.html.twig]

sonata_block:
  default_contexts: [cms]
  blocks:
    # Enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts: [admin]
    sonata.admin.block.search_result:
      contexts: [admin]

    sonata.block.service.text: ~
    sonata.block.service.rss: ~

    sonata.user.block.menu: ~ # used to display the menu in profile pages
    sonata.user.block.account: ~ # used to display menu option (login option)

    sonata.media.block.media: ~
    sonata.media.block.gallery: ~
    sonata.media.block.feature_media: ~
    capco_admin.blog.block.recent_posts: ~
    capco_admin.block.recent_contributions: ~
    Capco\AdminBundle\Block\HelpBlockService: ~

sonata_classification:
  class:
    tag: Capco\ClassificationBundle\Entity\Tag
    category: Capco\ClassificationBundle\Entity\Category
    collection: Capco\ClassificationBundle\Entity\Collection
    context: Capco\ClassificationBundle\Entity\Context
    media: Capco\MediaBundle\Entity\Media

sonata_intl:
  timezone:
    detectors:
      - capco.intl.timezone_detector.global
    locales:
      default: Europe/Paris
      fr-FR: Europe/Paris
      en-GB: Europe/London
      de-DE: Europe/Berlin

sonata_media:
  class:
    media: Capco\MediaBundle\Entity\Media
    gallery: Capco\MediaBundle\Entity\Gallery
    gallery_has_media: Capco\MediaBundle\Entity\GalleryHasMedia
    category: Capco\ClassificationBundle\Entity\Category
  default_context: default
  db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
  contexts:
    default: # the default context is mandatory
      providers:
        - sonata.media.provider.dailymotion
        - sonata.media.provider.youtube
        - sonata.media.provider.vimeo
        - sonata.media.provider.image
        - sonata.media.provider.file
      formats:
        small: { width: 100, quality: 70 }
        big: { width: 500, quality: 70 }
        blockHeader: { width: 750, height: 500, quality: 70 }
        project: { width: 360, height: 240, quality: 70 }
        form_radio: ~
        form: { height: 150, quality: 70 }
        idea: { height: 400, quality: 70 }
        proposal: { height: 400, quality: 70 }
        response: { height: 400, quality: 70 }
        logo: { height: 50, quality: 70 }
        socialIcon: { width: 50, height: 50, quality: 70 }
        homepageVideo: { width: 360, height: 240, quality: 70 }
        header_picto: { height: 100, quality: 70 }
        theme: { width: 360, height: 240, quality: 70 }
        slider: { width: 750, height: 300, quality: 70 }
        header: { width: 1280, quality: 70 }
        header_md: { width: 1024, quality: 70 }
        header_sm: { width: 800, quality: 70 }
        header_xs: { width: 640, quality: 70 }

    sonata_collection:
      providers:
        - sonata.media.provider.image

      formats:
        preview: { width: 100, quality: 100 }
        wide: { width: 820, quality: 100 }

    sonata_category:
      providers:
        - sonata.media.provider.image

      formats:
        preview: { width: 100, quality: 100 }
        wide: { width: 820, quality: 100 }

    sources:
      download:
        strategy: sonata.media.security.superadmin_strategy
        mode: http
      providers:
        - sonata.media.provider.file
        - sonata.media.provider.image
      formats: ~

  providers:
    image:
      thumbnail: sonata.media.thumbnail.liip_imagine
      adapter: sonata.media.adapter.image.imagick
    vimeo:
      thumbnail: sonata.media.thumbnail.liip_imagine
    youtube:
      thumbnail: sonata.media.thumbnail.liip_imagine
    dailymotion:
      thumbnail: sonata.media.thumbnail.liip_imagine
    file:
      service: sonata.media.provider.file
      resizer: false
      filesystem: sonata.media.filesystem.local
      cdn: sonata.media.cdn.server
      generator: sonata.media.generator.default
      thumbnail: sonata.media.thumbnail.format
      allowed_extensions:
        [
          'pdf',
          'txt',
          'rtf',
          'doc',
          'docx',
          'xls',
          'xlsx',
          'ppt',
          'pttx',
          'odt',
          'odg',
          'odp',
          'ods',
          'odc',
          'odf',
          'odb',
          'csv',
          'xml',
          'jpg',
          'jpeg',
          'png',
          'bmp',
          'tiff',
        ]
      allowed_mime_types:
        [
          'application/pdf',
          'application/x-pdf',
          'application/rtf',
          'text/html',
          'text/rtf',
          'text/plain',
          'image/*',
          'application/msword',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'application/vnd.ms-excel',
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'application/vnd.ms-powerpoint',
          ' application/vnd.openxmlformats-officedocument.presentationml.presentation',
          'application/vnd.oasis.opendocument.text',
          'application/vnd.oasis.opendocument.graphics',
          'application/vnd.oasis.opendocument.presentation',
          'application/vnd.oasis.opendocument.spreadsheet',
          'application/vnd.oasis.opendocument.chart',
          'application/vnd.oasis.opendocument.formula',
          'application/vnd.oasis.opendocument.database',
          'text/csv',
          'application/xml',
        ]
  cdn:
    server:
      path: / # http://media.sonata-project.org/
  filesystem:
    local:
      directory: '%kernel.root_dir%/../web/media'
      create: true

sonata_user:
  security_acl: true
  class:
    user: Capco\UserBundle\Entity\User
    group: Capco\UserBundle\Entity\Group
  admin:
    user:
      class: Capco\AdminBundle\Admin\UserAdmin
      controller: CapcoAdminBundle:User
      translation: CapcoAppBundle
