# Fetch xlf files from Loco: CapcoAppBundle.{locale}.xlf and validators.{locale}.xlf
translation_adapter_loco:
  projects:
    cap-collectif:
      # This key provides read-only access to our translations. 
      # It's suitable for deployment scripts and sharing download links with colleagues.
      # So we can keep it here.
      api_key: '926rGROkivvAoIO3ZJ0HiOh4529fIca3'
      domains: ['CapcoAppBundle', 'validators']

translation:
  locales: '%locales%'
  configs:
    app:
      dirs: ['%kernel.project_dir%/src']
      output_dir: '%kernel.project_dir%/translations'
      remote_storage: ['php_translation.adapter.loco']
