CreateProjectDistrictPayload:
  type: relay-mutation-payload
  config:
    fields:
      district:
        type: 'ProjectDistrict'
      districtEdge:
        type: 'ProjectDistrictEdge'
        description: 'The edge from the project district connection.'
      userErrors:
        type: '[UserError!]!'
        description: 'An unsuccessful mutation will return one or more `UserError` objects.'
