CreateProjectDistrictInput:
  type: input-object
  config:
    fields:
      geojson:
        type: GeoJSON
      displayedOnMap:
        type: Boolean
        defaultValue: false
      border:
        type: BorderStyleInput
      background:
        type: BackgroundStyleInput
      translations:
        type: '[InternalDistrictTranslationInput!]!'

