# Used to configure serialization for Gedmo LogEntry
Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [Logs, LogDetails]
    action:
      expose: true
      groups: [LogDetails]
    loggedAt:
      expose: true
      groups: [LogDetails]
    version:
      expose: true
      groups: [LogDetails]
