InternalVoteConnection:
    type: relay-connection
    config:
        name: VoteConnection
        nodeType: InternalVote
        connectionFields:
            totalCount:
                type: Int!
                description: Identifies the total count of items in the connection.
