VersionConnection:
  type: relay-connection
  config:
    nodeType: InternalVersion!
    connectionFields:
      totalCount:
        type: Int!
        description: Identifies the total count of items in the connection.
