PreviewProposalConnection:
  type: relay-connection
  config:
    name: ProposalConnection
    nodeType: PreviewProposal!
    connectionFields:
      totalCount:
        type: Int!
        description: Identifies the total count of items in the connection.
