PreviewReplyConnection:
  type: relay-connection
  config:
    name: ReplyConnection
    nodeType: PreviewReply!
    connectionFields:
      totalCount:
        type: Int!
        description: Identifies the total count of items in the connection.
