Archive:
  type: object
  config:
    description: 'A user personnal archive.'
    fields:
      id:
        type: 'ID!'
        description: 'The id of the archive.'
      requestedAt:
        type: 'DateTime!'
        description: 'When did the user requested his archive?'
      ready:
        type: 'Boolean!'
        description: 'Has the archive been generated?'
      deletedAt:
        type: 'DateTime'
        description: 'When the archive has been deleted?'
