InternalAppLogConnection:
    type: relay-connection
    config:
        name: AppLogConnection
        nodeType: InternalAppLog!
        connectionFields:
            totalCount:
                type: Int!
            newestLoggedAt:
                type: DateTime!
                description: 'newest logged action'
            oldestLoggedAt:
                type: DateTime!
                description: 'oldest logged action'
            userRoles:
                type: "[AppLogUserRole!]!"
                resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Query\\AppLogUserRoleResolver")'
