InternalShieldAdminForm:
  type: object
  config:
    name: ShieldAdminForm
    fields:
      shieldMode:
        description: 'Is shield mode is active?'
        type: 'Boolean!'
      introduction:
        description: 'Introduction text to show in shield page.'
        type: 'HTML'
      media:
        description: 'Image to show in shield page.'
        type: 'InternalMedia'
