InternalSectionQuestion:
  type: object
  inherits:
    - InternalQuestion
  config:
    name: SectionQuestion
    interfaces:
      - InternalQuestion
      - Node
    description: 'A section is just a title in a quiz without any possible answer.'
    fields:
      kind:
        resolve: 'section'
