ProposalCategory:
  type: object
  config:
    description: 'A proposal category'
    fields:
      id:
        type: 'ID!'
      name:
        type: 'String!'
      categoryImage:
        type: 'CategoryImage'
        description: 'Get the associated illustration of the category'
