InternalQuestionChoiceRanking:
  type: object
  config:
    name: QuestionChoiceRanking
    description: 'The choice ranking'
    fields:
      position:
        type: 'Int!'
        description: 'Identifies the position of the choice'
      responses:
        type: 'InternalResponseConnection!'
        argsBuilder: 'Relay::Connection'
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\QuestionChoice\\QuestionChoiceRankingResponseResolver", [value, args])'
        description: 'Identifies the responses of the choice.'
