Capco\AppBundle\Entity\ArgumentVote:
  attributes:
    argument:
      groups: [ElasticsearchVoteNestedArgument]
    getConsultation:
      type: object
      serialized_name: consultation
      groups: [ElasticsearchVoteNestedConsultation]
