Capco\AppBundle\Entity\OpinionVersionVote:
  attributes:
    value:
      groups: [OpinionVersions]
    opinionVersion:
      groups: [ElasticsearchVoteNestedVersion]
    getConsultation:
      type: object
      serialized_name: consultation
      groups: [ElasticsearchVoteNestedConsultation]
