Capco\AppBundle\Entity\OpinionType:
  attributes:
    id:
      groups: [Opinions, OpinionVersions, OpinionTypeDetails, ElasticsearchOpinionNestedOpinionType]
    title:
      groups: [Opinions, OpinionVersions, OpinionTypeDetails]
    subtitle:
      groups: [Opinions, OpinionVersions]
    color:
      groups: [Opinions, OpinionVersions]
    sourceable:
      groups: [Opinions, OpinionVersions, OpinionTypeDetails]
    versionable:
      groups: [Opinions, OpinionVersions, OpinionTypeDetails]
    linkable:
      groups: [Opinions, OpinionVersions, OpinionTypeDetails]
    voteWidgetType:
      groups: [Opinions, OpinionVersions, OpinionVersionPreviews, OpinionTypeDetails]
    commentSystem:
      groups: [Opinions, OpinionVersions, OpinionTypeDetails]
    votesThreshold:
      groups: [Opinions, OpinionVersions]
    votesHelpText:
      groups: [Opinions, OpinionVersions]
    votesThresholdHelpText:
      groups: [Opinions, OpinionVersions]
    appendixTypes:
      groups: [OpinionTypeDetails]
