Capco\AppBundle\Entity\Project:
    attributes:
        id:
            groups:
                [
                    Projects,
                    ElasticsearchProject,
                    ElasticsearchNestedProject,
                    ElasticsearchVoteNestedProject,
                    ElasticsearchCommentNestedProject,
                    ElasticsearchArgumentNestedProject,
                    ElasticsearchDebateArgumentNestedProject,
                    ElasticsearchSourceNestedProject,
                    ElasticsearchOpinionNestedProject,
                    ElasticsearchVersionNestedProject,
                    ElasticsearchReplyNestedProject,
                    ElasticsearchProposalNestedProject,
                    ElasticsearchEventNestedProject,
                ]
        title:
            groups: [Projects, ElasticsearchProject]
        authors:
            groups:
                [
                    ElasticsearchProjectNestedAuthor,
                    ElasticsearchArgumentNestedProject,
                    ElasticsearchDebateArgumentNestedProject,
                    ElasticsearchSourceNestedProject,
                    ElasticsearchOpinionNestedProject,
                    ElasticsearchVersionNestedProject,
                    ElasticsearchVoteNestedProject,
                    ElasticsearchProposalNestedProject,
                ]
        visibility:
            groups:
                [
                    Projects,
                    ElasticsearchProject,
                    ElasticsearchNestedProject,
                    ElasticsearchVoteNestedProject,
                    ElasticsearchCommentNestedProject,
                    ElasticsearchArgumentNestedProject,
                    ElasticsearchDebateArgumentNestedProject,
                    ElasticsearchSourceNestedProject,
                    ElasticsearchOpinionNestedProject,
                    ElasticsearchVersionNestedProject,
                    ElasticsearchProposalNestedProject,
                    ElasticsearchReplyNestedProject,
                ]
        canContribute:
            groups: [Projects]
        createdAt:
            groups: [Projects, ElasticsearchProject]
        updatedAt:
            groups: [Default]
        themes:
            groups: [Projects, ElasticsearchProjectNestedTheme]
        projectType:
            groups: [Projects, ElasticsearchProjectNestedProjectType]
        video:
            groups: [Projects]
        Cover:
            groups: [Default]
            serialized_name: cover
        participativeStep:
            groups: [Projects]
            serialized_name: hasParticipativeStep
        publishedAt:
            groups: [Projects, ElasticsearchProject]
        projectDistrictPositioners:
            serialized_name: districts
            groups: [ElasticsearchProjectNestedProjectDistrictPositioner]
        locale:
            groups: [Projects, ElasticsearchProject]
        elasticsearchTypeName:
            serialized_name: objectType
            groups: [ElasticsearchProject]
        owner:
            groups: [ElasticsearchProject]
        archived:
            groups: [ElasticsearchProject]
