Capco\AppBundle\Entity\ProposalForm:
  attributes:
    id:
      groups: [Proposals, ProposalForms, Elasticsearch]
    title:
      groups: [ProposalForms]
    titleHelpText:
      groups: [ProposalForms]
    description:
      groups: [ProposalForms]
    descriptionHelpText:
      groups: [ProposalForms]
    themeHelpText:
      groups: [ProposalForms]
    districtHelpText:
      groups: [ProposalForms]
    categoryHelpText:
      groups: [ProposalForms]
    addressHelpText:
      groups: [ProposalForms]
    summaryHelpText:
      groups: [ProposalForms]
    usingThemes:
      groups: [ProposalForms]
    usingCategories:
      groups: [ProposalForms]
    usingDistrict:
      groups: [ProposalForms]
    usingAddress:
      groups: [ProposalForms]
    themeMandatory:
      groups: [ProposalForms]
    categoryMandatory:
      groups: [ProposalForms]
    districtMandatory:
      groups: [ProposalForms]
    categories:
      groups: [ProposalForms]
    districts:
      groups: [ProposalForms]
    zoomMap:
      groups: [ProposalForms]
    latMap:
      groups: [ProposalForms]
    lngMap:
      groups: [ProposalForms]
    commentable:
      groups: [ProposalForms]
    costable:
      groups: [ProposalForms]
    proposalInAZoneRequired:
      groups: [ProposalForms]
    canContribute:
      serialized_name: isContribuable
      groups: [ProposalForms]
    getRealQuestions:
      serialized_name: fields
      groups: [ProposalForms]
