Capco\AppBundle\Entity\ProposalComment:
  attributes:
    getProposal:
      type: object
      serialized_name: proposal
      groups: [ElasticsearchNestedComment, ElasticsearchCommentNestedProposal]
