Capco\AppBundle\Entity\SourceCategory:
    attributes:
        id:
            groups: [Categories, Elasticsearch]
        title:
            groups: [Categories]
        slug:
            groups: [Categories]
