Capco\AppBundle\Entity\Status:
  attributes:
    id:
      groups: [Statuses, Proposals, Elasticsearch, ElasticsearchProposal]
    name:
      groups: [Statuses, Proposals, Elasticsearch]
    color:
      groups: [Statuses, Proposals]
