Capco\AppBundle\Entity\Steps\ProjectAbstractStep:
  attributes:
    id:
      groups: [ProjectAbstractSteps]
    project:
      groups: [ProjectAbstractSteps]
    step:
      groups: [ProjectAbstractSteps, Steps]
    position:
      groups: [ProjectAbstractSteps, Steps]
