Capco\AppBundle\Entity\Steps\AbstractStep:
  discriminator:
    type_property: step_type
    mapping:
      consultation: Capco\AppBundle\Entity\Steps\ConsultationStep
      presentation: Capco\AppBundle\Entity\Steps\PresentationStep
      other: Capco\AppBundle\Entity\Steps\OtherStep
      synthesis: Capco\AppBundle\Entity\Steps\SynthesisStep
      collect: Capco\AppBundle\Entity\Steps\CollectStep
      ranking: Capco\AppBundle\Entity\Steps\RankingStep
      selection: Capco\AppBundle\Entity\Steps\SelectionStep
      questionnaire: Capco\AppBundle\Entity\Steps\QuestionnaireStep
  attributes:
    id:
      groups: [Opinions, Proposals, Steps, SelectionStepId, Elasticsearch]
    title:
      groups: [Steps]
    isEnabled:
      groups: [Steps]
      serialized_name: enabled
    startAt:
      groups: [Steps]
    endAt:
      groups: [Steps]
    body:
      groups: [Steps]
    statuses:
      groups: [SelectionSteps, Statuses]
    getProjectId:
      groups: [Steps]
      serialized_name: projectId
    getPosition:
      groups: [Steps]
      serialized_name: position
    isOpen:
      groups: [Steps]
      serialized_name: open
    getType:
      groups: [StepTypes]
      seriealized_name: type
    isTimeless:
      groups: [Steps]
      serialized_name: timeless
