Capco\AppBundle\Entity\Theme:
  attributes:
    id:
      groups: [ThemeDetails, ElasticsearchTheme, ElasticsearchProposalNestedTheme, ElasticsearchProjectNestedTheme, ElasticsearchEventNestedTheme]
    title:
      groups: [Themes, ThemeDetails, ElasticsearchTheme]
    slug:
      groups: [Themes, ThemeDetails, ElasticsearchTheme]
    media:
      groups: [Default]
    isEnabled:
      groups: [ThemeDetails]
      serialized_name: enabled
