PreviewProjectOrderField:
  type: enum
  config:
    name: ProjectOrderField
    description: 'Ordering options for projects returned from the connection.'
    values:
      POPULAR:
        value: '@=constant("Capco\\AppBundle\\Enum\\ProjectOrderField::POPULAR")'
        description: 'Allows ordering a list of projects by their number of contributions.'
      PUBLISHED_AT:
        value: '@=constant("Capco\\AppBundle\\Enum\\ProjectOrderField::PUBLISHED_AT")'
        description: 'Allows ordering a list of projects by when they were published.'
