ProposalStepStatusColor:
    type: enum
    config:
        description: 'Different status type'
        values:
            INFO:
                description: 'Info color.'
                value: '@=constant("Capco\\AppBundle\\Enum\\StatusColor::INFO")'
            PRIMARY:
                description: 'Primary color.'
                value: '@=constant("Capco\\AppBundle\\Enum\\StatusColor::PRIMARY")'
            SUCCESS:
                description: 'Success color.'
                value: '@=constant("Capco\\AppBundle\\Enum\\StatusColor::SUCCESS")'
            WARNING:
                description: 'Warning color.'
                value: '@=constant("Capco\\AppBundle\\Enum\\StatusColor::WARNING")'
            DANGER:
                description: 'Danger color.'
                value: '@=constant("Capco\\AppBundle\\Enum\\StatusColor::DANGER")'
            DEFAULT:
                description: 'Default color.'
                value: '@=constant("Capco\\AppBundle\\Enum\\StatusColor::NORMAL")'
