Authorable:
  type: object
  decorator: true
  config:
    fields:
      viewerDidAuthor:
        type: 'Boolean'
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\User\\ViewerDidAuthorResolver", [value, getUser()])'
        description: 'Did the viewer author this entity.'
