Timestampable:
  type: object
  decorator: true
  config:
    fields:
      updatedAt:
        type: 'DateTime'
        description: 'Identifies the date and time when the object was last updated.'
      createdAt:
        type: 'DateTime!'
        description: 'Identifies the date and time when the object was created.'
