PreviewMutation:
  type: object
  config:
    description: 'This is the entry point into performing writes in the schema.'
    name: Mutation
    fields:
      addEvent:
        access: "@=hasRole('ROLE_USER')"
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: PreviewAddEventInput
          payloadType: PreviewAddEventPayload
          mutateAndGetPayload: '@=mutation("Capco\\AppBundle\\GraphQL\\Mutation\\AddEventMutation", [value, getUser()])'
      changeEvent:
        access: "@=hasRole('ROLE_USER')"
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: PreviewChangeEventInput
          payloadType: PreviewChangeEventPayload
          mutateAndGetPayload: '@=mutation("Capco\\AppBundle\\GraphQL\\Mutation\\ChangeEventMutation", [value, getUser()])'
      deleteEvent:
        access: "@=hasRole('ROLE_USER')"
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: PreviewDeleteEventInput
          payloadType: PreviewDeleteEventPayload
          mutateAndGetPayload: '@=mutation("Capco\\AppBundle\\GraphQL\\Mutation\\DeleteEventMutation", [value, getUser()])'
