PreviewContributionOrder:
  type: input-object
  config:
    name: ContributionOrder
    description: 'Ways in which lists of contributions can be ordered upon return.'
    fields:
      field:
        type: 'PreviewContributionOrderField!'
        defaultValue: 'CREATED_AT'
      direction:
        type: 'OrderDirection!'
        defaultValue: 'DESC'
