PublicConsultation:
  type: object
  inherits:
    - Node
  config:
    interfaces:
      - Node
    description: 'A consultation'
    name: Consultation
    fields:
      id:
        description: 'The ID of an object.'
        builder: 'Relay::GlobalId'
        builderConfig:
          typeName: Consultation
      title:
        type: 'String!'
        description: 'The title of the consultation.'
      contributors:
        type: 'PublicUserConnection!'
        description: 'A list of contributor associated with the consultation.'
        argsBuilder: 'Relay::Connection'
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Consultation\\ConsultationContributorsResolver", [value, args])'
      userHasVote:
        type: 'Boolean!'
        description: 'Whether the user has vote for a contribution in the related step of this consultation.'
        args:
          login:
            type: 'String!'
            description: "The user's login (for example, an email)."
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\ConsultationStep\\ConsultationStepUserHasVoteResolver", [value.getStep(), args])'
      votesCount:
        type: 'Int'
        description: 'The number of votes in the related step of this consultation.'
        deprecationReason: '@=service("Capco\\AppBundle\\GraphQL\\Deprecation").toString({startAt: "2019-09-01", reason: "In preparation for an upcoming change to the way we expose counters, this field will only be available inside a connection.", description: "Field `votesCount` will be removed.", supersededBy: "Use `votes.totalCount` instead."})'
