CheckboxRequirementInput:
    type: input-object
    config:
        description: 'Checkbox Requirement input'
        fields:
            requirementId:
                type: 'ID!'
                description: 'The Node ID of the requirement to modify.'
            value:
                type: 'Boolean!'
                description: 'The updated value of the requirement.'
