CommentOrder:
  type: input-object
  config:
    description: 'Ways in which lists of comments can be ordered upon return.'
    fields:
      field:
        type: 'CommentOrderField!'
        defaultValue: 'PUBLISHED_AT'
        description: 'The field in which to order nodes by.'
      direction:
        type: 'OrderDirection!'
        defaultValue: 'DESC'
        description: 'The direction in which to order nodes.'
