ContributionOrder:
  type: input-object
  config:
    description: 'Ways in which lists of contributions can be ordered upon return.'
    fields:
      field:
        type: 'ContributionOrderField!'
        defaultValue: 'POSITION'
      direction:
        type: 'OrderDirection!'
        defaultValue: 'DESC'
