InternalEventInput:
    type: input-object
    config:
        name: EventInput
        fields:
            startAt:
                type: 'String'
            endAt:
                type: 'String'
            authorEmail:
                type: 'String!'
            themes:
                type: '[String!]!'
            projects:
                type: '[String!]!'
            guestListEnabled:
                type: 'Boolean!'
            enabled:
                type: 'Boolean!'
            commentable:
                type: 'Boolean!'
            zipCode:
                type: 'String'
            address:
                type: 'String'
            customCode:
                type: 'String'
            city:
                type: 'String'
            country:
                type: 'String'
            translations:
                type: '[InternalEventTranslationInput]'
            title:
                type: 'String'
            body:
                type: 'HTML'
            link:
                type: 'URI'
            metaDescription:
                type: 'String'
            measurable:
                type: 'Boolean!'
                defaultValue: false
                description: 'Whether or not this event is registrations measurable.'
            maxRegistrations:
                type: 'Int'
                description: 'If measurable what is the max allowed registrations'
