# Because we can currently not create Input union in GraphQL, the ProjectStep input
# must have all posible fields for all different concrete implementations of a Step,
# that mean that all field that are non shared must be declared as nullable :(
# See https://github.com/graphql/graphql-spec/issues/488
# and https://github.com/graphql/graphql-spec/issues/627 for the RFC
ProjectStepInput:
    type: input-object
    config:
        fields:
            # AbstractStep fields
            type:
                type: 'ConcreteStepType!'
            id:
                type: 'ID'
            title:
                type: 'String!'
            label:
                type: 'String!'
            startAt:
                type: 'DateTime'
            endAt:
                type: 'DateTime'
            body:
                type: 'HTML'
            bodyUsingJoditWysiwyg:
                description: 'Is the body using Jodit Wysiwyg.'
                type: 'Boolean'
            metaDescription:
                type: 'String'
            customCode:
                type: 'String'
            isEnabled:
                type: 'Boolean!'
            requirements:
                type: '[StepRequirementInput!]!'
            requirementsReason:
                type: 'String'
            # Everything underneath is not common to every step, so they ALL must be nullable (see file header to understand why)
            # Timeless steps fields (the ones that use the `TimelessStepTrait` trait)
            # (actually: SelectionStep, CollectStep, QuestionnaireStep, ConsultationStep)
            timeless:
                type: 'Boolean'
            # ConsultationStep fields
            consultations:
                type: '[ID]'
            # VotableStep fields (the ones that use the `VoteThresholdTrait` and `VoteTypeTrait`
            # (actually: CollectStep and SelectionStep)
            votesHelpText:
                type: 'String'
            voteType:
                type: 'ProposalStepVoteType'
            budget:
                type: 'Float'
            votesLimit:
                type: 'Int'
                description: 'Maximum number of votes a user can submit.'
            votesMin:
                type: 'Int'
                description: 'Minimum number of votes a user must submit for his votes to be counted.'
            votesRanking:
                type: 'Boolean'
            voteThreshold:
                type: 'Int'
            defaultSort:
                type: 'ProposalSort'
            # SelectionStep fields
            allowAuthorsToAddNews:
                type: 'Boolean'
            allowingProgressSteps:
                type: 'Boolean'
            # statuses and defaultStatus are used only by CollectStep and SelectionStep
            statuses:
                type: '[StepStatusInput]'
            mainView:
                type: 'MainView'
                description: 'the default view : GRID, LIST or MAP'
            # CollectStep
            private:
                type: 'Boolean'
            proposalForm:
                type: 'ID'
            defaultStatus:
                type: 'ID'
            # QuestionnaireStep
            questionnaire:
                type: 'ID'
            footer:
                type: 'HTML'
            footerUsingJoditWysiwyg:
                description: 'Is the questionnaire footer using Jodit Wysiwyg.'
                type: 'Boolean'
            collectParticipantsEmail:
                type: 'Boolean'
            # RankingStep
            nbOpinionsToDisplay:
                type: 'Int'
            nbVersionsToDisplay:
                type: 'Int'
            # DebateStep
            articles:
                type: '[DebateArticleInput]'
            debateType:
                type: 'DebateType'
            debateContent:
                type: 'HTML'
            debateContentUsingJoditWysiwyg:
                type: 'Boolean'
            # DebateStep && QuestionnaireStep
            isAnonymousParticipationAllowed:
                type: 'Boolean'
            secretBallot:
                type: 'Boolean'
                description: 'Whether or not secret ballot is enable'
            publishedVoteDate:
                type: 'DateTime'
                description: 'If not null, the date to display vote count'
