ProposalOrder:
  type: input-object
  config:
    description: 'Ways in which proposal connections can be ordered.'
    fields:
      field:
        type: 'ProposalOrderField!'
        description: 'The field in which to order nodes by.'
      direction:
        type: 'OrderDirection!'
        defaultValue: 'ASC'
        description: 'The direction in which to order nodes.'
