ProposalFormNotificationsInput:
    type: input-object
    config:
        fields:
            onCreate:
                type: 'Boolean!'
            onUpdate:
                type: 'Boolean!'
            onDelete:
                type: 'Boolean!'
