StepOrder:
  type: input-object
  config:
    description: 'Ways in which lists of steps can be ordered upon return.'
    fields:
      field:
        type: 'StepOrderField!'
        defaultValue: 'POSITION'
        description: 'The field in which to order nodes by.'
      direction:
        type: 'OrderDirection!'
        defaultValue: 'DESC'
        description: 'The direction in which to order nodes.'
