UserOrder:
  type: input-object
  config:
    description: 'Ways in which lists of users can be ordered upon return.'
    fields:
      field:
        type: 'UserOrderField!'
        defaultValue: '@=constant("Capco\\AppBundle\\Enum\\SortField::CREATED_AT")'
        description: The field to order users by.
      direction:
        type: 'OrderDirection!'
        defaultValue: '@=constant("Capco\\AppBundle\\Enum\\OrderDirection::DESC")'
        description: The ordering direction.
