VoteInput:
  type: input-object
  config:
    description: 'A vote'
    fields:
      id:
        type: 'ID!'
        description: 'The vote id.'
      anonymous:
        type: 'Boolean!'
        description: 'Update the vote privacy.'
