Capco\UserBundle\Entity\User:
  attributes:
    id:
      groups:
        [
          UserId,
          Elasticsearch,
          ElasticsearchNestedProject,
          ElasticsearchArgumentNestedProject,
          ElasticsearchSourceNestedProject,
          ElasticsearchOpinionNestedProject,
          ElasticsearchVersionNestedProject,
          ElasticsearchVoteNestedProject,
          ElasticsearchReplyNestedProject,
          ElasticsearchProposalNestedProject,
          ElasticsearchProjectNestedAuthor,
          ElasticsearchEventNestedProject,
          ElasticsearchDebateArgumentNestedAuthor,
        ]
    slug:
      groups: [Default, Elasticsearch]
    media:
      groups: [UsersInfos, UserDetails]
    vip:
      groups: [UsersInfos, UserDetails, Elasticsearch]
    userType:
      groups: [UsersInfos, Elasticsearch]
      serialized_name: userType
    biography:
      groups: [Default, sonata_api_read, sonata_api_write, sonata_search, UsersInfos]
    username:
      serialized_name: username
      type: string
      groups: [Default, Elasticsearch, sonata_api_read, sonata_api_write, sonata_search, UsersInfos]
    displayName:
      serialized_name: displayName
      type: string
      groups: [UserDetails, UsersInfos]
    uniqueIdentifier:
      serialized_name: uniqueId
      type: string
      groups: [UserDetails, UsersInfos]
    email:
      groups: [Elasticsearch]
    isEmailConfirmed:
      groups: [Elasticsearch]
    isConsentInternalCommunication:
      groups: [Elasticsearch]
    firstname:
      groups: [Elasticsearch]
    lastname:
      groups: [Elasticsearch]
    createdAt:
      serialized_name: createdAt
      groups: [Elasticsearch]
    roles:
      groups: [Elasticsearch]
    enabled:
      groups: [Elasticsearch]
      type: boolean
    elasticsearchTypeName:
      serialized_name: objectType
      groups: [Elasticsearch]
