AddContactFormPayload:
  type: relay-mutation-payload
  config:
    description: 'Add a new contact form.'
    fields:
      contactForm:
        type: 'InternalContactForm!'
        description: 'The contact form created.'
