AddOpinionVoteInput:
  type: relay-mutation-input
  config:
    description: 'Add a vote for an opinion/version.'
    fields:
      opinionId:
        type: 'ID!'
        description: 'The Node ID of the opinion/version to vote.'
      value:
        type: 'YesNoPairedVoteValue!'
        description: 'The vote value.'
