AddOpinionVotePayload:
  type: relay-mutation-payload
  config:
    fields:
      vote:
        type: 'YesNoPairedVote'
      voteEdge:
        type: 'YesNoPairedVoteEdge'
      viewer:
        type: 'InternalUser!'
      previousVoteId:
        type: 'ID'
