AddProposalVotePayload:
    type: relay-mutation-payload
    config:
        fields:
            vote:
                type: 'InternalProposalUserVote!'
            viewer:
                type: 'InternalUser!'
            voteEdge:
                type: 'InternalProposalVoteEdge!'
