AddSmsCreditPayload:
    type: relay-mutation-payload
    config:
        description: 'Payload of addSmsCredit mutation.'
        fields:
            smsCredit:
                type: 'InternalSmsCredit'
                description: 'The created sms credit.'
            errorCode:
                type: 'AddSmsCreditErrorCode'
                description: 'Available errors for the mutation.'
