AddSourceInput:
  type: relay-mutation-input
  config:
    description: 'Input type of AddSource'
    fields:
      sourceableId:
        type: 'ID!'
        description: 'The Sourceable ID to source.'
      body:
        type: 'String!'
        description: 'The contents of the source body.'
      category:
        type: 'ID!'
        description: 'The category of the source.'
      link:
        type: 'URI!'
      title:
        type: 'String!'
