AddUsersInGroupInput:
  type: relay-mutation-input
  config:
    description: 'Add many users in a specific group.'
    fields:
      users:
        type: '[ID!]!'
        description: 'Users that will be added to the group.'
      groupId:
        type: 'ID!'
        description: 'The concerned group id.'
