AddUsersToGroupFromEmailPayload:
  type: relay-mutation-payload
  config:
    fields:
      importedUsers:
        type: '[InternalUser]!'
        description: 'List of imported users.'
      notFoundEmails:
        type: '[Email]!'
        description: "List of emails that didn't match an existing user."
      alreadyImportedUsers:
        type: '[InternalUser]!'
        description:
          'If an email from your list is already associated to a user who is in the chosen group, it will be in this field.'
