ChangeProposalContentInput:
  type: relay-mutation-input
  config:
    description: 'Update a proposal'
    fields:
      id:
        type: 'ID!'
        description: 'The proposal id'
      draft:
        type: 'Boolean'
        description: "Pass 'true' to keep your proposal in draft state, otherwise we admit that you want to publish it."
      title:
        type: 'String'
        description: 'The new proposal title'
      body:
        type: 'HTML'
        description: 'The new proposal body'
      summary:
        type: 'String'
        description: 'The new proposal summary'
      author:
        type: 'ID'
        description: 'The author id (ROLE_SUPER_ADMIN allowed only)'
      theme:
        type: 'String'
        description: 'The theme id (feature themes enabled)'
      category:
        type: 'String'
        description: 'The category id'
      district:
        type: 'String'
        description: 'The district id (feature districts enabled)'
      address:
        type: 'String'
        description: 'The address geocoded by google'
      responses:
        type: '[ResponseInput]'
        description: 'The custom fields responses'
      media:
        type: 'ID'
        description: 'Current media id'
