ChangeMapProviderTokenInput:
  type: relay-mutation-input
  config:
    description: 'Input type of ChangeMapProviderToken.'
    fields:
      provider:
        type: 'MapTokenProvider!'
        description: 'The name of the provider the new token will be set'
      publicToken:
        type: 'String!'
        description: 'The new public token'
      secretToken:
        type: 'String'
        description: 'The new secret token'
