ChangeUserNotificationsConfigurationInput:
  type: relay-mutation-input
  config:
    description: 'Change a user notifications preferences'
    fields:
      onProposalCommentMail:
        type: 'Boolean!'
        description: 'The new proposal comment notification value'
      consentExternalCommunication:
        type: 'Boolean!'
        description: 'The new external consent for communication'
      consentInternalCommunication:
        type: 'Boolean!'
        description: 'The new internal consent for communication'
