ChangeVersionInput:
  type: relay-mutation-input
  config:
    description: 'The input type of changeVersion.'
    fields:
      versionId:
        type: 'ID!'
        description: 'The version Node id.'
      body:
        type: 'String'
        description: 'Updated version body.'
      title:
        type: 'String'
        description: 'Updated version title.'
      comment:
        type: 'String'
        description: 'Updated version comment.'
