ChangeSourceInput:
  type: relay-mutation-input
  config:
    description: 'The input type of changeSource.'
    fields:
      sourceId:
        type: 'ID!'
        description: 'The source id.'
      body:
        type: 'String'
        description: 'The contents of the source body.'
      category:
        type: 'ID'
        description: 'The contents of the source category.'
      title:
        type: 'String'
        description: 'The contents of the source title.'
      link:
        type: 'URI'
        description: 'The contents of the source link.'
