DeleteSourcePayload:
  type: relay-mutation-payload
  config:
    fields:
      deletedSourceId:
        type: 'ID'
        description: 'The deleted ID.'
      sourceable:
        type: 'Sourceable'
        description: 'The parent of the deleted source.'
