DeleteCommentPayload:
  type: relay-mutation-payload
  config:
    fields:
      deletedCommentId:
        type: 'ID'
      commentable:
        type: 'Commentable'
      userErrors:
        type: '[UserError]'
        description: 'An unsuccessful mutation will return one or more `UserError` objects.'
