InternalAddEventInput:
  type: relay-mutation-input
  inherits:
    - PreviewAddEventInput
  config:
    name: AddEventInput
    description: 'Input type of addEvent.'
    fields:
      enabled:
        type: 'Boolean'
        defaultValue: true
        description: 'Whether or not this event is published.'
      media:
        type: 'ID'
        description: 'The media to illustrate the event.'
      metaDescription:
        type: 'String'
        description: 'The metadescription of the event page.'
      commentable:
        type: 'Boolean'
        defaultValue: true
        description: 'Whether or not this event is commentable.'
      # TODO rename to externalRegistrationUrl ?
      link:
        type: 'String'
        description: 'The contents of the event external registration link.'
      # TODO rename to googleMapsAddress ?
      addressJson:
        type: 'String'
        description: 'The contents of the event addressJson.'
      customCode:
        type: 'String'
        description: 'The contents of the event customCode.'
      # cannot add access in type: relay-mutation-input
      projects:
        type: '[ID]'
        description: 'An array of Node IDs of projects associated to this event.'
      themes:
        type: '[ID]'
        description: 'An array of Node IDs of themes associated to this event.'
      guestListEnabled:
        type: 'Boolean!'
        defaultValue: false
        description: 'Whether or not this event is allow registrations.'
      author:
        type: 'ID'
        description: 'The Node ID of the author for this event.'
