InternalReviewEventInput:
  type: relay-mutation-input
  inherits:
  config:
    name: ReviewEventInput
    description: 'Input type of ReviewEvent'
    fields:
      id:
        type: 'ID!'
        description: 'The ID of the Event to review.'
      comment:
        type: 'String'
        description: 'The details of reason why the review is refused'
      refusedReason:
        type: 'EventRefusedReason'
        description: 'Kind of review is refused.'
      status:
        type: 'EventReviewStatus!'
        description: 'The status of review.'
