InternalUpdateOauth2SSOConfigurationInput:
  type: relay-mutation-input
  inherits:
    - InternalWithOauth2SSOConfiguration
  config:
    description: 'Update an oauth2 configuration'
    fields:
      id:
        description: 'The ID of oauth2 configuration that needs to be updated.'
        type: 'ID!'
