InternalChangeEventInput:
  type: relay-mutation-input
  inherits:
    - InternalAddEventInput
  config:
    name: ChangeEventInput
    description: 'Input type of ChangeEvent'
    fields:
      id:
        type: 'ID!'
        description: 'The ID of the Event to modify.'
