RemoveProposalVoteInput:
  type: relay-mutation-input
  config:
    description: 'Remove a vote for a proposal in a contribuable step.'
    fields:
      proposalId:
        type: 'ID!'
        description: 'The Node ID of the proposal to unvote.'
      stepId:
        type: 'ID!'
        description: 'The Node ID of the contribuable step.'
