RemoveContactFormPayload:
  type: relay-mutation-payload
  config:
    description: 'Remove a new contact form.'
    fields:
      deletedContactFormId:
        type: 'ID!'
        description: 'Id of the deleted contact form.'
