RemoveProposalVotePayload:
  type: relay-mutation-payload
  config:
    fields:
      step:
        type: 'ProposalStep!'
      proposal:
        type: 'Proposal!'
      viewer:
        type: 'InternalUser!'
