UpdateRegistrationFormQuestionsPayload:
  type: relay-mutation-payload
  config:
    description: 'Payload type of UpdateRegistrationFormQuestions mutation.'
    fields:
      registrationForm:
        type: 'InternalRegistrationForm'
