UpdateFollowOpinionPayload:
  type: relay-mutation-payload
  config:
    fields:
      follower:
        type: 'Follower'
      followerEdge:
        type: 'FollowerEdge'
      opinion:
        type: 'Opinion'
