UpdateProfilePasswordPayload:
  type: relay-mutation-payload
  config:
    fields:
      user:
        type: 'InternalUser!'
        description: 'The user who just have been updated'
      error:
        type: 'String'
        description: 'The error'
