UpdateProfilePasswordInput:
  type: relay-mutation-input
  config:
    description: 'Update your password'
    fields:
      current_password:
        type: 'String!'
        description: 'The current password'
      new_password:
        type: 'String!'
        description: 'The new password'
