Capco\AppBundle\Entity\SSO\Oauth2SSOConfiguration:
  ssoOauth2:
    id: 'ssoOauth2'
    name: 'Cap collectif Oauth2 Provider'
    enabled: false
    clientId: 'account'
    secret: '***REMOVED***'
    authorizationUrl: 'https://keycloak.cap-collectif.com/auth/realms/master/protocol/openid-connect/auth'
    accessTokenUrl: 'https://keycloak.cap-collectif.com/auth/realms/master/protocol/openid-connect/token'
    userInfoUrl: 'https://keycloak.cap-collectif.com/auth/realms/master/protocol/openid-connect/userinfo'
    logoutUrl: 'https://keycloak.cap-collectif.com/auth/realms/master/protocol/openid-connect/logout'
    profileUrl: 'https://keycloak.cap-collectif.com/auth/realms/master/account'
