joli_typo:
  presets:
    default:
      fixers: [Ellipsis, Dimension, Dash, FrenchQuotes, FrenchNoBreakSpace, CurlyQuote, Trademark]
      locale: fr_FR
    en:
      fixers: [Ellipsis, Dimension, Dash, EnglishQuotes, CurlyQuote, Trademark]
      locale: en_GB
