services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  _instanceof:
    Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface:
      tags: ['overblog_graphql.resolver']

  Capco\AppBundle\GraphQL\Resolver\:
    resource: '%kernel.project_dir%/src/Capco/AppBundle/GraphQL/Resolver/*'
    exclude: '%kernel.project_dir%/src/Capco/AppBundle/GraphQL/Resolver/{GlobalIdResolver.php,UserIsGrantedResolver.php}'

  Capco\AppBundle\GraphQL\Resolver\Questionnaire\QuestionnaireExportResultsUrlResolver:
    $projectDir: '%kernel.project_dir%'

  # This is not a resolver but a voter, rename and move this elsewhere
  Capco\AppBundle\GraphQL\Resolver\UserIsGrantedResolver:
    autowire: true
    public: true

  # Public services :
  Capco\AppBundle\GraphQL\Deprecation:
    autowire: true
    public: true
  Capco\AppBundle\GraphQL\Resolver\GlobalIdResolver:
    public: true

  Capco\AppBundle\GraphQL\Resolver\Media\MediaUrlResolver:
    bind:
      $routerRequestContextHost: '%router.request_context.host%'
      $assetsHost: '%assets_host%'
