services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Capco\AppBundle\Notifier\:
    resource: '%kernel.root_dir%/../src/Capco/AppBundle/Notifier/*'
    exclude: '%kernel.root_dir%/../src/Capco/AppBundle/Notifier/BaseNotifier.php'

  Capco\AppBundle\Notifier\ProposalNotifier:
    public: true

  Capco\AppBundle\Notifier\FOSNotifier:
    public: true

  Capco\AppBundle\Notifier\ContactNotifier:
    public: true

  Capco\AppBundle\Notifier\UserNotifier:
    public: true

  Capco\AppBundle\Notifier\ProjectNotifier:
    public: true

  Capco\AppBundle\Notifier\ContributionNotifier:
    public: true

  Capco\AppBundle\Notifier\ReportNotifier:
    public: true

  Capco\AppBundle\Notifier\FollowerNotifier:
    public: true
