services:
  capco.abstract_vote.repository:
    class: Capco\AppBundle\Repository\AbstractVoteRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:AbstractVote']

  capco.argument.repository:
    class: Capco\AppBundle\Repository\ArgumentRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Argument']

  capco.registration_form.repository:
    class: Capco\AppBundle\Repository\RegistrationFormRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:RegistrationForm']

  capco.abstract_question.repository:
    class: Capco\AppBundle\Repository\AbstractQuestionRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Questions\AbstractQuestion']

  capco.blog.post.repository:
    class: Capco\AppBundle\Repository\PostRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Post']

  capco.collect_step.repository:
    class: Capco\AppBundle\Repository\CollectStepRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Steps\CollectStep']

  capco.consultation_step_type.repository:
    class: Capco\AppBundle\Repository\ConsultationStepTypeRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Steps\ConsultationStepType']

  capco.district.repository:
    class: Capco\AppBundle\Repository\DistrictRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:District']

  capco.event.repository:
    class: Capco\AppBundle\Repository\EventRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Event']

  capco.highlighted.repository:
    class: Capco\AppBundle\Repository\HighlightedContentRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:HighlightedContent']

  capco.menu_item.repository:
    class: Capco\AppBundle\Repository\MenuItemRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:MenuItem']

  capco.opinion.repository:
    class: Capco\AppBundle\Repository\OpinionRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Opinion']

  capco.reporting.repository:
    class: Capco\AppBundle\Repository\ReportingRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Reporting']

  capco.opinion_type.repository:
    class: Capco\AppBundle\Repository\OpinionTypeRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:OpinionType']

  capco.comment.repository:
    class: Capco\AppBundle\Repository\ProposalRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Comment']

  capco.proposal.repository:
    class: Capco\AppBundle\Repository\ProposalRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Proposal']

  capco.idea_vote.repository:
    class: Capco\AppBundle\Repository\IdeaVoteRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:IdeaVote']

  capco.proposal_selection_vote.repository:
    class: Capco\AppBundle\Repository\ProposalSelectionVoteRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:ProposalSelectionVote']

  capco.proposal_collect_vote.repository:
    class: Capco\AppBundle\Repository\ProposalCollectVoteRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:ProposalCollectVote']

  capco.opinion_vote.repository:
    class: Capco\AppBundle\Repository\OpinionVoteRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:OpinionVote']

  capco.question_choice.repository:
    class: Capco\AppBundle\Repository\QuestionChoiceRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:QuestionChoice']

  capco.response.repository:
    class: Capco\AppBundle\Repository\AbstractResponseRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Responses\AbstractResponse']

  capco.section.repository:
    class: Capco\AppBundle\Repository\SectionRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Section']

  capco.selection_step.repository:
    class: Capco\AppBundle\Repository\SelectionStepRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Steps\SelectionStep']

  capco.site_color.repository:
    class: Capco\AppBundle\Repository\SiteColorRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:SiteColor']

  capco.site_image.repository:
    class: Capco\AppBundle\Repository\SiteImageRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:SiteImage']

  capco.site_parameter.repository:
    class: Capco\AppBundle\Repository\SiteParameterRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:SiteParameter']

  capco.theme.repository:
    class: Capco\AppBundle\Repository\ThemeRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Theme']

  capco.user_type.repository:
    class: Capco\UserBundle\Repository\UserTypeRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoUserBundle:UserType']

  capco.user.repository:
    class: Capco\UserBundle\Repository\UserRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoUserBundle:User']

  capco.video.repository:
    class: Capco\AppBundle\Repository\VideoRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Video']

  capco.project.repository:
    class: Capco\AppBundle\Repository\ProjectRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Project']

  capco.abstract_step.repository:
    class: Capco\AppBundle\Repository\AbstractStepRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Steps\AbstractStep']

  capco.consultation_step.repository:
    class: Capco\AppBundle\Repository\ConsultationStepRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Steps\ConsultationStep']

  capco.progress_step.repository:
    class: Capco\AppBundle\Repository\ProgressStepRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:Steps\ProgressStep']

  capco.proposal_category.repository:
    class: Capco\AppBundle\Repository\ProposalCategoryRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['CapcoAppBundle:ProposalCategory']
