services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Capco\AppBundle\Search\:
    resource: '%kernel.root_dir%/../src/Capco/AppBundle/Search/*'
  #    exclude: '%kernel.root_dir%/../src/Capco/AppBundle/{}'

  capco.search.global_search:
    class: Capco\AppBundle\Search\GlobalSearch
    public: true

  Capco\AppBundle\Search\EventSearch:
    class: Capco\AppBundle\Search\EventSearch
    public: true

  capco.search.user_search:
    class: Capco\AppBundle\Search\UserSearch
    public: true
