services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Capco\AppBundle\Utils\:
    resource: '%kernel.root_dir%/../src/Capco/AppBundle/Utils/*'
  #    exclude: '%kernel.root_dir%/../src/Capco/AppBundle/{}'
  Capco\AppBundle\GraphQL\ConnectionTraversor:
    public: true

  Capco\AppBundle\Utils\Map:
    public: true
    arguments:
      $apiSeverKey: '%google_maps_key_server%'

  pmill\Doctrine\Hydrator\ArrayHydrator:
    arguments: ['@doctrine.orm.default_entity_manager']

  EmailChecker\EmailChecker:
    arguments: ['@EmailChecker\Adapter\FileAdapter']

  EmailChecker\Adapter\FileAdapter:
    arguments: ['%kernel.root_dir%/config/throwable_emails.txt']
