CssJSON:
  type: custom-scalar
  config:
    description: 'A string containing CSS.'
    serialize: ["Capco\\AppBundle\\GraphQL\\Type\\CssJSONType", 'serialize']
    parseValue: ["Capco\\AppBundle\\GraphQL\\Type\\CssJSONType", 'parseValue']
    parseLiteral: ["Capco\\AppBundle\\GraphQL\\Type\\CssJSONType", 'parseLiteral']
