PublicPublishable:
  type: interface
  inherits:
    - Node
  config:
    name: Publishable
    description: 'Entities that can be published.'
    resolveType: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Publishable\\PublishableTypeResolver", [value])'
    fields:
      published:
        type: 'Boolean!'
        description: 'Whether or not the entity is published.'
        resolve: '@=value.isPublished()'
      publishableUntil:
        type: 'DateTime'
        description: 'Identifies when the entity can no more be published.'
        resolve: '@=value.getPublishableUntil()'
      publishedAt:
        type: 'DateTime'
        description: 'Identifies when the entity was published at.'
        resolve: '@=value.getPublishedAt()'
      notPublishedReason:
        type: 'NotPublishedReason'
        description: 'Reason that the entity is not published.'
        resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Publishable\\PublishableNotPublishedReasonResolver", [value])'
